# Generated by Django 2.2.13 on 2020-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=512)),
                ('is_internal', models.BooleanField(default=False)),
            ],
        ),
    ]
